netgen_layouts:
    pagelayout: 'base.html.twig'

    value_types:
        doctrine_recipe:
            name: Recipe
            manual_items: false

    query_types:
        latest_recipes:
            name: 'Latest Recipes'